services:
  tor-hs:
    build: .
    volumes:
      - tor-hs-data:/var/lib/tor/hidden_service
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  tor-hs-data:
